/* Generated by Edge Impulse
*
* Permission is hereby granted, free of charge, to any person obtaining a copy
* of this software and associated documentation files (the "Software"), to deal
* in the Software without restriction, including without limitation the rights
* to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
* copies of the Software, and to permit persons to whom the Software is
* furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
* SOFTWARE.
*/

#ifndef _EI_CLASSIFIER_ANOMALY_CLUSTERS_H_
#define _EI_CLASSIFIER_ANOMALY_CLUSTERS_H_

#include "edge-impulse-sdk/anomaly/anomaly.h"

// (before - mean) / scale
const float ei_classifier_anom_scale[EI_CLASSIFIER_ANOM_AXIS_SIZE] = { 2.5379544598024237, 2.5356518923048537 };
const float ei_classifier_anom_mean[EI_CLASSIFIER_ANOM_AXIS_SIZE] = { 33.491101717544815, 33.13586820182154 };

const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[EI_CLASSIFIER_ANOM_CLUSTER_COUNT] = { { { -1.1726380586624146, -1.2775377035140991 }, 0.5905796405801942 }
, { { 1.0082519054412842, 1.0099613666534424 }, 0.32519931936363605 }
, { { -0.16198138892650604, -0.1580936312675476 }, 0.20614544046439676 }
, { { -0.5241966843605042, -0.465036541223526 }, 0.39682169910927095 }
, { { 0.15970589220523834, 0.17202316224575043 }, 0.20968950925176386 }
, { { -2.1241917610168457, -2.1184442043304443 }, 0.4180597557406639 }
, { { 0.47632813453674316, 0.5231330394744873 }, 0.32401182287899666 }
, { { 1.8441334962844849, 1.7892986536026 }, 0.6036183797218999 }
};

#endif // _EI_CLASSIFIER_ANOMALY_CLUSTERS_H_
